// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgaQSDQI_TDqH02YJ8UICvbUArOKDC_Es',
    appId: '1:597845976782:web:761619f7edb2a15f34529f',
    messagingSenderId: '597845976782',
    projectId: 'login-app-56b9d',
    authDomain: 'login-app-56b9d.firebaseapp.com',
    storageBucket: 'login-app-56b9d.appspot.com',
    measurementId: 'G-8LXS4958V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvIiMdUQFsRXzBBXk-J16D2Y7CA-fix4c',
    appId: '1:597845976782:android:e5747447eca634be34529f',
    messagingSenderId: '597845976782',
    projectId: 'login-app-56b9d',
    storageBucket: 'login-app-56b9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgFLulDm9xamOZgVOUz5p7EOkBfpJfRvY',
    appId: '1:597845976782:ios:eeb01ce5cfdace5634529f',
    messagingSenderId: '597845976782',
    projectId: 'login-app-56b9d',
    storageBucket: 'login-app-56b9d.appspot.com',
    iosClientId: '597845976782-dh8k4vmdoqsnog628dc3ics8hpmo96cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgFLulDm9xamOZgVOUz5p7EOkBfpJfRvY',
    appId: '1:597845976782:ios:eeb01ce5cfdace5634529f',
    messagingSenderId: '597845976782',
    projectId: 'login-app-56b9d',
    storageBucket: 'login-app-56b9d.appspot.com',
    iosClientId: '597845976782-dh8k4vmdoqsnog628dc3ics8hpmo96cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginApp',
  );
}
